name: Django CI

on:
  pull_request:
    branches: [ "main" ]

env:
  BASE64_ENCODED_ENV: ${{ secrets.NEO_ENV_FILE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch .env file
      run: |
        echo '${{ env.BASE64_ENCODED_ENV }}' > .env
    - name: Run Tests
      run: |
        python manage.py test
