name: Django CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch .env file
      run: |
        echo ${{ secrets.NEO_ENV_FILE }} | base64 -d > .env
    - name: Run Tests
      run: |
        python manage.py test
    - name: Build the images and start the containers
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml up -d
    - name: Stop containers
      if: always()
      run: docker-compose -f docker-compose.yml down
